services:
  nginx:
    image: nginx:latest
    container_name: nginx-fichiers
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
      - /var/www/fichiers:/usr/share/nginx/html:ro
    restart: always