services:
  nginx:
    image: nginx:latest
    container_name: nginx-fichiers
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./fichiers:/usr/share/nginx/html:ro
    restart: always